### ISSUE TITLE
Misc AWS Issues

### ISSUE THREAD

**Issue by tyler-ground** [BigDataBoutique/elasticsearch-cloud-deploy#85]
Packer Error:  provisioner 1: 'only' specified builder 'amazon-ebs' not found

When running packer build -only=amazon-ebs -var-file=variables.json elasticsearch7-node.packer.json

I see that only amazon-ebs line was added a few days ago

**Comment by tyler-ground** [comment]
Changing it to aws and updating the packer.json for only aws appears to have resolved it.

**Comment by tyler-ground** [comment]
install-cloud-plugin was also looking for PACKER_BUILD_NAME EC2 (but it's aws) .  The line actually errored out altogether for me complaining about "[[".

**Comment by tyler-ground** [comment]
Seems like elasticsearch isn't getting the password either (but grafana and cerberos are)

**Comment by tyler-ground** [comment]
!!! Also, all the node types are getting the client heap size:
    heap_size              = var.client_heap_size

**Comment by tyler-ground** [comment]
I can send out a PR for these issues next week after I monitor the cluster to see how it's doing.

**Comment by synhershko** [comment]
Cool, thanks @tyler-ground , @shaigbdb please review those as well

**Comment by tyler-ground** [comment]
Found more problems.  Not sure how to fix these:
1) I added a data node to the first group and it wanted to modify all my data volumes
2) So I added to the last group... looked good except when it deployed it didn't attach the new volume and instead it setup the primary 8 GB volume.  My 200 GB data volume was sitting unused

**Comment by synhershko** [comment]
@tyler-ground last issue you mentioned should be fixed by #86 which I just merged

**Comment by tyler-ground** [comment]
Thanks @synhershko !

**Comment by shaigbdb** [comment]
The heap size issue is also fixed now, other than several subnets for the same zone which isn't supported everything should be fixed.

**Comment by tyler-ground** [comment]
oh wicked!  I was going to fix this but I'm still having a few issues that I wanted to investigate first.

I'll close out this ticket!  Thanks!
